Use symlinc instead of parent's folder lookup
If I use the parent's folder lookup, `truffle test` fails.

Error sample
```
$ truffle test
Using network 'test'.

Compiling your contracts...
===========================
> Compiling ./test/TestSpecialPlanetTokenShop.sol

  TestSpecialPlanetTokenShop
Error: Callback was already called.
```

---

Original commit (chain-contracts): 03d1eaba404f1678c2bf471f44c5571cd05b8e14